Fix #85 Create CodeQL Wultra GitHub Action Parent
wultra/wultra-infrastructure pull request #29
Opened 2023-07-10 12:43 UTC by jandusil

- Add new workflow file as parent workflow to perform codeql analysis

2023-07-10 18:05 UTC, jandusil commented
I have tested it on powerauth-server project. Here is the run
https://github.com/wultra/powerauth-server/actions/runs/5511357179

.. and here is the PR using this PR in powerauth-server

2023-07-10 18:29 UTC, zcgandcomp requested changes

2023-07-10 18:29 UTC, zcgandcomp commented on .github/workflows/codeql-analysis.yml
> +          category: "/language:${{ inputs.languages }}"
This should be a parameter from the matrix.

2023-07-11 09:36 UTC, zcgandcomp approved these changes
Looks OK.

2023-07-11 10:52 UTC, merged